name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: mockserver
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: mocks-api
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install libpq-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Test with pytest
      working-directory: ./mockserver
      run: |
        python manage.py test

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/head/develop') || (github.ref == 'refs/head/staging') || (github.ref == 'refs/head/master')
    steps:
    - uses: actions/checkout@v1
    - name: Log in to Docker Registry
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Builds Docker image
      run: |
        docker build -t ldelelis/mockserver:${GITHUB_REF##*/} .
    - name: Pushes built Docker image
      run: |
        docker push ldelelis/mockserver:${GITHUB_REF##*/}
    - name: Logs out from Docker Registry
      run: |
        docker logout
